name : shariyerShazan

on:
   push: 
      branches: [main]

jobs:
   firstJob: 
      runs-on: ubuntu-latest

      steps:
         - name: shazan
           run: echo "Shazan 1st github action workflow"
         - name: priya
           run: echo "Priya 2nd github action workflow"
